{
  "ID": "oval:org.debian:def:20087264",
  "Class": "vulnerability",
  "Metadata": {
    "Title": "CVE-2008-7264",
    "AffectedList": [
      {
        "Family": "unix",
        "Platform": "Debian GNU/Linux 10",
        "Product": "python-pyftpdlib"
      }
    ],
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2008-7264",
        "RefURL": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2008-7264"
      }
    ],
    "Description": "The ftp_QUIT function in ftpserver.py in pyftpdlib before 0.5.0 allows remote authenticated users to cause a denial of service (file descriptor exhaustion and daemon outage) by sending a QUIT command during a disallowed data-transfer attempt.",
    "Debian": {
      "MoreInfo": ""
    }
  },
  "Criteria": {
    "Operator": "AND",
    "Criterias": [
      {
        "Operator": "OR",
        "Criterias": [
          {
            "Operator": "AND",
            "Criterias": null,
            "Criterions": [
              {
                "Negate": false,
                "TestRef": "oval:org.debian.oval:tst:2",
                "Comment": "all architecture"
              },
              {
                "Negate": false,
                "TestRef": "oval:org.debian.oval:tst:3216",
                "Comment": "python-pyftpdlib DPKG is earlier than 0"
              }
            ]
          }
        ],
        "Criterions": null
      }
    ],
    "Criterions": [
      {
        "Negate": false,
        "TestRef": "oval:org.debian.oval:tst:1",
        "Comment": "Debian 10 is installed"
      }
    ]
  }
}