{
  "debianbug": 942514,
  "description": "pam-python before 1.0.7-1 has an issue in regard to the default environment variable handling of Python, which could allow for local root escalation in certain PAM setups.",
  "releases": {
    "bullseye": {
      "fixed_version": "1.0.7-1",
      "repositories": {
        "bullseye": "1.0.9-2"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "buster": {
      "fixed_version": "1.0.6-1.1+deb10u1",
      "repositories": {
        "buster": "1.0.6-1.1+deb10u1",
        "buster-security": "1.0.6-1.1+deb10u1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "sid": {
      "fixed_version": "1.0.7-1",
      "repositories": {
        "sid": "1.0.9-2"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "stretch": {
      "fixed_version": "1.0.6-1.1+deb9u1",
      "repositories": {
        "stretch": "1.0.6-1.1+deb9u1",
        "stretch-security": "1.0.6-1.1+deb9u1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    }
  },
  "scope": "local"
}