{
  "description": "An issue was discovered in py-lmdb 0.97. There is a divide-by-zero error in the function mdb_env_open2 if mdb_env_read_header obtains a zero value for a certain size field. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker.",
  "releases": {
    "bullseye": {
      "repositories": {
        "bullseye": "1.0.0-1"
      },
      "status": "open",
      "urgency": "unimportant"
    },
    "sid": {
      "repositories": {
        "sid": "1.0.0-1"
      },
      "status": "open",
      "urgency": "unimportant"
    },
    "stretch": {
      "repositories": {
        "stretch": "0.86-1"
      },
      "status": "open",
      "urgency": "unimportant"
    }
  },
  "scope": "local"
}