{
  "debianbug": 944605,
  "description": "psutil (aka python-psutil) through 5.6.5 can have a double free. This occurs because of refcount mishandling within a while or for loop that converts system data into a Python object.",
  "releases": {
    "bullseye": {
      "fixed_version": "5.6.7-1",
      "repositories": {
        "bullseye": "5.7.3-1"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "buster": {
      "nodsa": "Minor issue",
      "nodsa_reason": "",
      "repositories": {
        "buster": "5.5.1-1"
      },
      "status": "open",
      "urgency": "low"
    },
    "sid": {
      "fixed_version": "5.6.7-1",
      "repositories": {
        "sid": "5.8.0-1"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "stretch": {
      "nodsa": "Minor issue",
      "nodsa_reason": "",
      "repositories": {
        "stretch": "5.0.1-1"
      },
      "status": "open",
      "urgency": "low"
    }
  },
  "scope": "local"
}